---

dependencies:
  - role: base/docker
  - role: base/ansible_dependencies
    dependency_roles:
      - src: "git+https://github.com/Aura-healthcare/ansible-role-grafana-in-docker"
        version: master
