---

- include_role:
    name: .galaxy/ansible-role-grafana-in-docker
  vars:
    grafana_container_name: "{{ aura_monitoring_platform_container }}"
    grafana_docker_networks:
      - name: "{{ aura_docker_network }}"
    datasources:
      - datasource_name: "{{ aura_time_series_db_type }} {{ aura_physio_data_db_name }}"
        datasource_type: "{{ aura_time_series_db_type }}"
        datasource_database: "{{ aura_physio_data_db_name }}"
        datasource_hostname: "{{ aura_time_series_db_container }}"
        datasource_port: "{{ aura_time_series_db_port }}"
      - datasource_name: "{{ aura_time_series_db_type }} {{ aura_internal_db_data_db_name }}"
        datasource_type: "{{ aura_time_series_db_type }}"
        datasource_database: "{{ aura_internal_db_data_db_name }}"
        datasource_hostname: "{{ aura_time_series_db_container }}"
        datasource_port: "{{ aura_time_series_db_port }}"

- name : Copy templated Dashboard file
  become: true
  template: src="templates/_internal_statistics-1537517934443.json" dest="{{ grafana_dashboards_location_on_host }}" mode=0644

- name : Copy templated Home Dashboard file
  become: true
  template: src="templates/home_dashboard.json" dest="{{ grafana_dashboards_location_on_host }}" mode=0644

- name : Copy templated user zoom dashboard file
  become: true
  template: src="templates/user_zoom_dashboard.json" dest="{{ grafana_dashboards_location_on_host }}" mode=0644

- name : Copy templated outliers dashboard file
  become: true
  template: src="templates/outliers_dashboard.json" dest="{{ grafana_dashboards_location_on_host }}" mode=0644